---
- name: Install common DevOps tools and configure apache2
  hosts: ubuntu_servers
  become: yes

  vars:
    git_username: "naveen-ops-hub"
    git_email: "karampatinaveen@gmail.com"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install common DevOps tools
      apt:
        name:
          - net-tools      # for netstat
          - apache2        # web server
          - git            # version control
          - curl           # testing APIs, downloading files
          - wget           # file downloads
          - unzip          # extract zip files
          - vim            # editor
          - htop           # process monitoring
          - tree           # directory structure
          - python3-pip    # python package manager
          - docker.io      # container runtime
        state: present

    - name: Configure git username
      command: git config --system user.name "{{ git_username }}"

    - name: Configure git email
      command: git config --system user.email "{{ git_email }}"

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>DevOps Test Page</title></head>
          <body>
          <h1>Hello from Ansible!</h1>
          <p>This is a DevOps test page deployed on {{ inventory_hostname }}.</p>
          <p>Apache is running successfully 🚀</p>
          <p>Installed tools: netstat, git, curl, docker, etc.</p>
          </body>
          </html>

    - name: Ensure apache2 is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
