---
- name: "Get Junos OS configuration (set format) and upload to Swift"
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos
    - openstack.cloud

  tasks:
    - name: "Get selected configuration (set format)"
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: set
        dest: "/tmp/{{ inventory_hostname }}-{{ ansible_date_time.date }}"

    - name: "Upload set file to Swift"
      openstack.cloud.object:
        container: backup-set
        name: "{{ inventory_hostname }}-{{ ansible_date_time.date }}"
        filename: "/tmp/{{ inventory_hostname }}-{{ ansible_date_time.date }}"
        state: present

- name: "Get Junos OS configuration (json) and upload to Swift"
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos
    - openstack.cloud

  tasks:
    - name: "Get json config"
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: json
        dest: "/tmp/{{ inventory_hostname }}-{{ ansible_date_time.date }}.json"

    - name: "Upload json file to Swift"
      openstack.cloud.object:
        container: backup-json
        name: "{{ inventory_hostname }}-{{ ansible_date_time.date }}.json"
        filename: "/tmp/{{ inventory_hostname }}-{{ ansible_date_time.date }}.json"
        state: present
