---
- name: "Get Junos OS configuration in set and JSON formats"
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos
    - openstack.cloud

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: junos
    backup_dir: "/runner"
    swift_set_container: "backup-set"
    swift_json_container: "backup-json"
    backup_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Get Junos committed configuration in SET format
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: set
      register: set_output
      check_mode: no

    - name: Save SET output locally
      copy:
        content: "{{ set_output.stdout | join('\n') }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ backup_date }}.set"

    - name: Get Junos committed configuration in JSON format
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: json
      register: json_output
      check_mode: no

    - name: Save JSON output locally
      copy:
        content: "{{ json_output.stdout | to_nice_json }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ backup_date }}.json"

    - name: Upload SET backups to Swift container
      os_object:
        state: present
        container: "{{ swift_set_container }}"
        name: "{{ inventory_hostname }}-{{ backup_date }}.set"
        filename: "{{ backup_dir }}/{{ inventory_hostname }}-{{ backup_date }}.set"

    - name: Upload JSON backups to Swift container
      os_object:
        state: present
        container: "{{ swift_json_container }}"
        name: "{{ inventory_hostname }}-{{ backup_date }}.json"
        filename: "{{ backup_dir }}/{{ inventory_hostname }}-{{ backup_date }}.json"
