---
- name: "Get Junos OS configuration and upload to Swift"
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos
    - openstack.cloud

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: junos
    ansible_user: "{{ lookup('env', 'JUNOS_USER') | default('L1-User') }}"
    ansible_password: "{{ lookup('env', 'JUNOS_PASS') | default('L1!0gin#123') }}"
    swift_set_container: "backup-set"
    swift_json_container: "backup-json"
    backup_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

  tasks:

    - name: Get Junos committed configuration in SET format
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: set
      register: set_output
      check_mode: no

    - name: Upload SET backup to Swift container
      os_object:
        state: present
        container: "{{ swift_set_container }}"
        name: "{{ inventory_hostname }}-{{ backup_date }}.set"
        content: "{{ set_output.stdout | join('\n') }}"

    - name: Get Junos committed configuration in JSON format
      junipernetworks.junos.junos_config:
        retrieve: committed
        format: json
      register: json_output
      check_mode: no

    - name: Upload JSON backup to Swift container
      os_object:
        state: present
        container: "{{ swift_json_container }}"
        name: "{{ inventory_hostname }}-{{ backup_date }}.json"
        content: "{{ json_output.stdout | to_nice_json }}"
