---
- name: Get Junos OS configuration in json format
  hosts: mytest
  collections:
    - junipernetworks.junos
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: junos
    ansible_connection: netconf
 
  tasks:
    - name: Get selected configuration hierarchies and save to file
      junipernetworks.junos.junos_config:
        provider:
          host: "{{ inventory_hostname }}"
        retrieve: committed
        dest: "/root/backup/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}.json"
        format: json
      register: config_result
 
- name: Store set data in Swift container
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Storing set data in Swift container
      os_object:
        state: present
        container: backup-set
        filename: "/root/backup/{{ item }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}"
      loop: "{{ groups['mytest'] }}"
 
- name: Store json data in Swift container
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Storing json data in Swift container
      os_object:
        state: present
        container: backup-json
        filename: "/root/backup/{{ item }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}.json"
      loop: "{{ groups['mytest'] }}"
