---
- name: "Get Junos OS configuration in set format"
  hosts: mytest
  connection: netconf
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: junos
    ansible_connection: netconf
  tasks:
    - name: "Backup configuration in set format"
      junipernetworks.junos.junos_config:
        backup: true
        backup_options:
          dir_path: "/runner"
          filename: "{{ inventory_hostname }}-{{ lookup('pipe','date +%Y-%m-%d') }}"
        src_format: "set"

- name: "Upload set backup to Swift container"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Storing set backup in Swift container"
      os_object:
        state: present
        container: backup-set
        name: "{{ item }}-{{ lookup('pipe','date +%Y-%m-%d') }}"
        filename: "/runner/{{ item }}-{{ lookup('pipe','date +%Y-%m-%d') }}"
      loop: "{{ groups['mytest'] }}"
