---
- name: "Get Junos OS configuration in set format."
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: junos
    ansible_connection: netconf
  tasks:
    - name: "Get selected configuration hierarchies and save to file"
      junipernetworks.junos.junos_command:
        commands:
          - "show lldp neighbors"
          - "show interfaces terse"
          - "show chassis environment"
          - "show chassis hardware"
          - "show version"
          - "show system alarms"
          - "show chassis alarms"
          - "show bgp summary"
          - "show chassis fpc"
          - "show cli history"
        display: text
      register: junos_output
      check_mode: no   # disable check mode (avoids "invalid rpc" error)

    - name: Save output to file
      copy:
        content: "{{ junos_output.stdout | join('\n\n') }}"
        dest: "/root/naveen/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y-%m-%d') }}.txt"
