---
- name: "Get Junos OS information and save to file"
  hosts: mytest
  connection: netconf
  gather_facts: no
  collections:
    - junipernetworks.junos

  tasks:
    - name: "Run show version and check to see if output contains Juniper"
      junipernetworks.junos.junos_command:
        commands:
          - "show version"
        format: text
      register: version_output

    - name: "Debug version output"
      debug:
        var: version_output

    - name: "Run multiple commands and save to file"
      junipernetworks.junos.junos_command:
        commands:
          - "show lldp neighbors"
          - "show interfaces terse"
          - "show chassis environment"
          - "show chassis hardware"
          - "show system alarms"
          - "show chassis alarms"
          - "show bgp summary"
          - "show chassis fpc"
          - "show cli history"
        dest: "/root/naveen/{{ inventory_hostname }}-{{ lookup('pipe','date +%Y-%m-%d') }}"
        format: text
